travis:
  secure:
    BINSTAR_TOKEN: lkHHd/YhBiCJ9xlR8pme0XZ5OijrZNmG0BIrZkxu8E4QxPhKY/0kVCKeClPqwEUaKQZz5G7G2McwVSVNzmnP7x55hyrHl5iIEeZUb08gWks4+TD63o9R9twThMbzpSozqG7zV7ETW640UTMNaN1bOlwLw4OILcRuxdPEIcwJMX9n+otbM4e8uyhRk87OwUFV9xp6mjhVzL04vjNGo+R6dROwPwXDAl3mCcT3x/ARQXUZ8NOu1gwf7Sk3Hg/zxmLWBn5CRN6MG9zie6ycXji/j/sfcUiFcs4TMJshDUX8+aGv2u2oXKHfBN1CLG8DmZPi+k4h3RXS3HSUNyw2dK2i6Nt2Un850WEG1REhwfwbjNYNiqS5JEDLcZu/HWyf9eFXsda9RZBfWzyZgI9uIBESb8s0z3wXLAJ9hiT8CZ9IIibM+P+lPjLd6JPoP0Vms0GpPdxbxWVCKdM3mf4iyWZrTvk+70hlfhdLjWBDIes6WyQivJRU950Mpoy3IN4aDaoThWvsN3igIFDsT7in9SL6zCjifYu+Vdq+KfzqE71Nx54ahc40jBYmXiOOX235Y1YEMKnx1E8SFwSLNXAm9MZD9bTh6OMUEheeV/0i4GRAp4mZTrzvUAdSHjwoYHu/tU7oeDT+nqfhcl0WOeUej0DEIeOrzGU0bbHMObuP5GBaMWk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
